services:
  - type: web
    name: park-guide-backend
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn park_guide.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
